language: objective-c
osx_image: xcode10.3
script:
  - xcodebuild test -project DataArchive.xcodeproj -scheme DataArchive-Package ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)